apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.mesh.serviceName }}
spec:
  hosts:
    - {{ .Values.mesh.serviceName }}
    - {{ .Values.mesh.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
    - mesh
  http:
    - name: hello-failover-internal
      retries:
        attempts: {{ .Values.mesh.retries.attempts }}
        perTryTimeout: {{ .Values.mesh.retries.perTryTimeout }}
        retryOn: {{ .Values.mesh.retries.retryOn }}
      route:
        - destination:
            host: {{ .Values.mesh.serviceName }}
            port:
              number: 8080
---
{{- if .Values.mesh.ingress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.mesh.ingress.gatewayName }}
  labels:
    app.kubernetes.io/name: {{ .Values.mesh.ingress.gatewayName }}
    app.kubernetes.io/part-of: istio-failover-demo
    app.kubernetes.io/component: ingress
spec:
  selector:
    {{- toYaml .Values.mesh.ingress.selector | nindent 4 }}
  servers:
    - hosts:
        - {{ .Values.mesh.ingress.host }}
      port:
        name: {{ .Values.mesh.ingress.port.name }}
        number: {{ .Values.mesh.ingress.port.number }}
        protocol: {{ .Values.mesh.ingress.port.protocol }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.mesh.ingress.gatewayName }}
spec:
  hosts:
    - {{ .Values.mesh.ingress.host }}
  gateways:
    - {{ .Values.mesh.ingress.gatewayName }}
  http:
    - name: hello-failover-external
      retries:
        attempts: {{ .Values.mesh.retries.attempts }}
        perTryTimeout: {{ .Values.mesh.retries.perTryTimeout }}
        retryOn: {{ .Values.mesh.retries.retryOn }}
      route:
        - destination:
            host: {{ .Values.mesh.serviceName }}
            port:
              number: 8080
{{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.mesh.serviceName }}
spec:
  host: {{ .Values.mesh.serviceName }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
      localityLbSetting:
        enabled: true
        failoverPriority:
          {{- toYaml .Values.mesh.failoverPriority | nindent 10 }}
    outlierDetection:
      consecutive5xxErrors: {{ .Values.mesh.outlierDetection.consecutive5xxErrors }}
      interval: {{ .Values.mesh.outlierDetection.interval }}
      baseEjectionTime: {{ .Values.mesh.outlierDetection.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.mesh.outlierDetection.maxEjectionPercent }}
  subsets:
    {{- range .Values.mesh.subsets }}
    - name: {{ .name }}
      labels:
        failover-role: {{ .failoverRole }}
    {{- end }}
