{{- if .Values.serviceMeshMember.enabled }}
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: {{ .Values.serviceMeshMember.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  controlPlaneRef:
    name: {{ .Values.serviceMeshMember.controlPlane.name }}
    namespace: {{ .Values.serviceMeshMember.controlPlane.namespace }}
{{- end }}
