spring.application.name=hello-world
server.port=8080

app.instance-name=primary
app.reply-message=hello from primary version 0.1.0
app.version=0.1.0
app.fault.enabled=true
app.fault.trigger-input=fail-primary
app.fault.status-code=503

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never
management.prometheus.metrics.export.enabled=true

info.app.name=${spring.application.name}
info.app.version=${app.version}
