apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-client
  labels:
    app: mesh-client
    failover-role: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-client
      failover-role: primary
  template:
    metadata:
      labels:
        app: mesh-client
        failover-role: primary
    spec:
      containers:
      - name: mesh-client
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        command:
        - /bin/sh
        - -c
        - sleep infinity
